nome = input("Digite seu nome completo: ").strip()
print("Analisando seu nome...")
print("Seu nome em letras maiúsculas é {}.".format(nome.upper()))
print("Seu nome em letras minúsculas é {}.".format(nome.lower()))
print("Seu nome tem {} letras ao todo.".format(len(nome.replace(" ", ""))))
dividido = nome.split()
print("Seu primeiro nome é {} e ele tem {} letras.".format(dividido[0], len(dividido[0])))
